CREATE EXTENSION IF NOT EXISTS postgis;

-- Generated SQL
CREATE TYPE "role" AS ENUM (
  'driver',
  'restaurant_manager'
);

CREATE TYPE "menu_item_availability" AS ENUM (
  'available',
  'unavailable'
);

CREATE TYPE "charger_status" AS ENUM (
  'available',
  'reserved_not_in_use',
  'reserved_charging',
  'charging_stopped'
);

CREATE TYPE "food_status" AS ENUM (
  'pending',
  'cooking',
  'ready',
  'picked_up'
);

CREATE TYPE "connector_type" AS ENUM (
  'CCS',
  'CHAdeMO',
  'Type 2'
);

CREATE TYPE "charging_payment_status" AS ENUM (
  'not_payed',
  'payed'
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar(50) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "role" role NOT NULL DEFAULT 'driver'
);

CREATE TABLE "settings" (
  "settings_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "customer_id" int NOT NULL,
  "vehicle_model" varchar(255) NOT NULL,
  "connector_type" connector_type NOT NULL,
  "desired_soc" int NOT NULL DEFAULT 0,
  "cuisines" varchar(50)[],
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "stations" (
  "station_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "location" geography NOT NULL,
  "address" varchar(255) NOT NULL
);

CREATE TABLE "restaurants" (
  "restaurant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "station_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "location" geography NOT NULL,
  "name" varchar(50) NOT NULL,
  "cuisines" varchar(50)[],
  "address" varchar(255) NOT NULL
);

CREATE TABLE "chargers" (
  "charger_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "station_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "status" charger_status NOT NULL,
  "connector_type" connector_type NOT NULL,
  "power" int NOT NULL
);

CREATE TABLE "menu_items" (
  "menu_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "restaurant_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "name" varchar(50) NOT NULL,
  "details" varchar(255) NOT NULL,
  "price" float NOT NULL,
  "minutes_to_prepare" int NOT NULL,
  "availability" menu_item_availability NOT NULL
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "customer_id" int NOT NULL,
  "restaurant_id" int NOT NULL,
  "total_price" float NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "customer_eta" timestamp NOT NULL DEFAULT (now()),
  "food_status" food_status NOT NULL DEFAULT 'pending'
);

CREATE TABLE "reservations" (
  "reservation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "charger_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "reservation_start" timestamp NOT NULL DEFAULT (now()),
  "reservation_end" timestamp NOT NULL DEFAULT (now()),
  "time_of_payment" timestamp DEFAULT null,
  "final_price_of_charge" float DEFAULT null
);

CREATE TABLE "order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "menu_item_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "name" varchar(255) NOT NULL,
  "details" varchar(255) NOT NULL,
  "price" float NOT NULL
);

CREATE TABLE "notifications" (
  "notification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL
);

ALTER TABLE "settings" ADD FOREIGN KEY ("customer_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "restaurants" ADD FOREIGN KEY ("station_id") REFERENCES "stations" ("station_id") ON DELETE CASCADE;

ALTER TABLE "chargers" ADD FOREIGN KEY ("station_id") REFERENCES "stations" ("station_id") ON DELETE CASCADE;

ALTER TABLE "menu_items" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("restaurant_id") ON DELETE CASCADE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "orders" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("restaurant_id") ON DELETE CASCADE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("charger_id") REFERENCES "chargers" ("charger_id") ON DELETE CASCADE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_items" ("menu_item_id") ON DELETE CASCADE;


-- Manual SQL


-- Trigger functions

